// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	EMBEDDING_KV: KVNamespace;
	ENVIRONMENT: "dev" | "staging" | "demo" | "production";
	ALLOWED_ORIGINS: "https://dev.skillpassports.com" | "https://stag.skillpassports.com" | "https://demo.skillpassports.com" | "https://skillpassport.com,https://www.skillpassport.com";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	RATE_LIMITER: RateLimit;
	AI: Ai;
}
